version: v1.0
name: Deploy to Production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
blocks:
  - name: Kubectl Apply
    task:
      jobs:
        - name: apply
          commands:
            - checkout
            - kubectl apply -n jpw -f deploy.yaml
